- xrft/tests/test_xrft.py
Found the problem causing #52, and fixed it so tests now pass. 
It was an issue with the tests not the code. It was because iterating over a dataarray iterates over the values in the array, rather than over the names of the dimensions as the test assumed. 
How did the failing tests get merged? Did this behaviour change in xarray at some point? I'm using the development master version of xarray. Does xrft need to specify minimum versions of its dependencies?
> Fixed test_dft_1d so it passes

- xrft/tests/test_xrft.py
- xrft/xrft.py
Added an option to do a real fft instead of assuming that you always wish to retain negative frequencies.
Required wrapping `np.fft.rfftn` instead of `np.fft.fftn`, and setting `shift=False` if `real=True`.
> Option to use real fft

- setup.cfg
- xrft/tests/test_xrft.py
- xrft/xrft.py
I implemented #57 and the tests are passing. I made the `real` argument so that the user gives a list of the order how they would want the input transposed and returns the real FFT with the same order of dimensions as the original input, e.g. the argument of `dim=['time'], real=['Y','X','time']` to take the real FFT over `time` for a dataset with dimensions of `['time','Y','X']` would return `['freq_time','Y','X']`.
I don't use real FFTs that much so would be great if @TomNicholas and @dcherian could try it out and see how it suits their needs :)
> implementing real=coords

- doc/conf.py
- doc/whats-new.rst
- xrft/tests/test_xrft.py
- xrft/xrft.py
I inserted a for loop for the `isotropic` functions so that it can take arrays up to 4 dimensions.
> for loop for azimuthal averaging in isotropic functions

- .travis.yml
- setup.py
- xrft/xrft.py
I think this should fix issues #78 and #83 .
> Update 'real' argument for xarray

- .travis.yml
- xrft/tests/test_xrft.py
- xrft/xrft.py
This PR attemps to fix several issues related to isospectrum computations:
- breaks with dask arrays (dask bincount does not handle mixed types arguments)
- breaks with extra dimensions
See [gist](https://gist.github.com/apatlpo/54f61a697d426cd5522ed1d18db66f13) for illustration of failures
I also propose a modest refactoring which consists in adding an isotropize methods that average spectra or crossspectra azimuthaly.
This method is called by isotropic_powerspectrum and isotropic_crossspectrum
There are still some improvements that could be made:
-  isotropize could be made more robust
-  the present form is not lazy (because dask bincount is not able to predict array size)
If you believe this PR is worth anything, let me know, I can finetune, even though weeks to come are going to be …
> isospectrum debugging / refactoring

- setup.py
I'm excited to give xrft a try!
I noticed that future and docrep are no longer imported in xrft.py, but pandas
and scipy are, so this PR updates dependencies accordingly in setup.py.
> Fix dependencies listed under install_requires

- .travis.yml
- setup.py
- xrft/tests/test_xrft.py
- xrft/xrft.py
I added some checks to the `cftime` convention based on #99 but I don't have much confidence whether this is robust enough for other options than `noleap`. If others think this PR is good to merge, I'll merge it and work on releasing a new version #97.
> cftime convention for noleap

- xrft/tests/test_xrft.py
- xrft/xrft.py
The term `N` in the `density=True` normalisation is computed from the chunk sizes rather than dimension sizes when `chunks_to_segments=True`.
Closes #102
-   [x]  Bug fix (non-breaking change which fixes an issue)
> Fix normalisation of power spectra density when `chunks_to_segments=True`

- ci/environment-py3.6.yml
- ci/environment-py3.7.yml
- ci/environment-py3.8.yml
- setup.py
- xrft/tests/test_xrft.py
- xrft/xrft.py
I implemented @shoyer 's amazing `numpy_groupies` hack to parallelize the isotropization of spectra. This addresses issues #9 and #87 .
> Parallelize isotropize

- xrft/xrft.py
I moved the call `import numpy_groupies` only to when `isotropic` functions are called.
> Making numpy_groupies an extra requirement

- xrft/tests/test_xrft.py
- xrft/xrft.py
A PR to double the power and cross spectrum when `real` is called in order to adhere with `scipy.signal.periodogram(return_onesided=True)` convention. This addresses issue #105 .
> Making FFT conventions similar to scipy

- xrft/detrend.py
- xrft/tests/test_detrend.py
- xrft/tests/test_xrft.py
- xrft/xrft.py
When window weighting is applied with the power_spectrum functions, the input `dim` is passed directly to `_apply_window` to determine the correction weights. But `_apply_window` expects `dims` to be a list. This PR copies the same logic applied in `dft` and `idft` into `_apply_window` to force `dims` to be a list.
Closes #142
> Force dim to be a list in _apply_window

- doc/DFT-iDFT_example.ipynb
- xrft/tests/test_xrft.py
- xrft/xrft.py
Added the flag to allow for energy/amplitude correction for isotropic spectrum as is done for the `power_spectrum()` and `cross_spectrum()`.
> Energy correction for isotropic spectrum

- xrft/detrend.py
- xrft/tests/test_detrend.py
- xrft/tests/test_xrft.py
- xrft/xrft.py
This addresses issue #159 and updates the `axis_num` when `detrend='linear'` because the latter changes the order of the dimensions.
> Update `axis_num` when `detrend='linear'` is taken

- xrft/xrft.py
A PR to initiate a deprecation cycle for `xrft.dft` and to replace it with `xrft.fft`. As the tests all pass using `dft`, none of the previous behaviors should break with only the warning messages changing.
> Deprecating `dft` and replacing it with `fft`

- xrft/tests/test_xrft.py
- xrft/xrft.py
This PR has two additions (see issue #162):
- raises an error in `xrft.fft()`  when there are multiple coordinates attached to the same dimensions (added in `xrft.py`)
- tests for the above error (added to `test_xrft.py`)
Note that I haven't contributed code for awhile, so a thorough read-through of what I've done would be great. Also, I have never used 'code-style' before, but I got a message stating that "all jobs have failed" and I'm not quite sure how to address this. So let me know if I need to update something here!
> Raise error for non-dimensional coordinates

- setup.cfg
* removed `setuptools` from `install_requires`
* `setup_requires` info is specified in `pyproject.toml`, so removed it
* added initial groups for `cftime` and `numpy_groupies`
> Fix `requires` in `setup.cfg`

- xrft/tests/test_xrft.py
- xrft/xrft.py
This PR removes the deprecated `False` flags from the functions and sets them to `True` as default. This addresses issue #177 .
> Linting for a new version release

- .github/workflows/ci.yaml
- ci/environment.yml
- setup.cfg
- xrft/tests/test_xrft.py
Refactoring due to deprecations in numpy and pandas.
> Refactoring for Python 3.12

- xrft/xrft.py
this change allows for coordinates with precision below 1 second. The diff is then divided by 1e9 to maintain the apparent standard for time being expressed in seconds.
This is a potential quick fix for #203.
> change _diff_coord to use nanosecond precision
